name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign review and assignees
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: Surviveyeomi, Ryu-GeonWoo
          github-token: ${{ secrets.GITHUB_TOKEN }}
